FROM python:3.7-slim

# Install dependencies
COPY requirements.txt .
RUN python -m pip install -r requirements.txt

# Set up directory for action server
WORKDIR /app
COPY . .

USER 1001

CMD ["run", "actions", "--actions", "actions", "--port", "5055"]
